name: Dialyzer

on: pull_request

jobs:
  check_dialyzer:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir/Erlang Environment
        uses: ./.github/actions

      - name: Dialyzer
        run: mix dialyzer