name: Check Format Elixir Code

on: pull_request

jobs:
  check_format:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir/Erlang Environment
        uses: ./.github/actions

      - name: Check Format
        run: mix format --check-formatted
