name: Check Lint Elixir Code

on: pull_request

jobs:
  check_lint:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir/Erlang Environment
        uses: ./.github/actions

      - name: Check Lint
        run: mix credo suggest --strict
