name: Check Security Elixir Code

on: pull_request

jobs:
  check_security:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir/Erlang Environment
        uses: ./.github/actions

      - name: Check Security
        run: mix sobelow --config