name: Release Tag

on: workflow_dispatch

jobs:
 release_tag:
  runs-on: ubuntu-20.04

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Elixir/Erlang Environment
      uses: ./.github/actions

    - name: Git config
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Release
      run: mix git_ops.release --yes

    - name: Push tag
      run: git push --follow-tags