name: Tests

on: pull_request

env:
  MIX_ENV: test

jobs:
  check_tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir/Erlang Environment
        uses: ./.github/actions

      - name: Check coverage and tests
        run: mix coveralls.html
        env:
          MIX_ENV: ${{ env.MIX_ENV }}

    services:
      postgres:
        image: postgres:15.2
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: food_order_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
